import { int, index, mysqlEnum, mysqlTable, text, timestamp, uniqueIndex, varchar, decimal } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const clientProfiles = mysqlTable("client_profiles", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().unique(), trainerUserId: int("trainerUserId").notNull(), goals: text("goals"), startingWeight: varchar("startingWeight", { length: 32 }), labsNote: text("labsNote"), status: mysqlEnum("status", ["active", "paused", "cancelled"]).default("active").notNull(), disclaimerAcknowledgedAt: timestamp("disclaimerAcknowledgedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (table) => ({ trainerIndex: index("client_profiles_trainer_idx").on(table.trainerUserId) }));
export const invites = mysqlTable("invites", { id: int("id").autoincrement().primaryKey(), trainerUserId: int("trainerUserId").notNull(), email: varchar("email", { length: 320 }).notNull(), token: varchar("token", { length: 96 }).notNull().unique(), status: mysqlEnum("status", ["pending", "accepted", "expired"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), acceptedAt: timestamp("acceptedAt") });
export const courses = mysqlTable("courses", { id: int("id").autoincrement().primaryKey(), title: varchar("title", { length: 180 }).notNull(), description: text("description").notNull(), accent: varchar("accent", { length: 32 }).default("lime").notNull(), status: mysqlEnum("status", ["draft", "published"]).default("published").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const modules = mysqlTable("modules", { id: int("id").autoincrement().primaryKey(), courseId: int("courseId").notNull(), position: int("position").notNull(), title: varchar("title", { length: 180 }).notNull(), summary: text("summary").notNull(), contentType: mysqlEnum("contentType", ["video", "reading"]).default("reading").notNull(), contentUrl: text("contentUrl"), durationMinutes: int("durationMinutes").default(10).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ coursePositionIndex: uniqueIndex("modules_course_position_idx").on(table.courseId, table.position) }));
export const courseAccess = mysqlTable("course_access", { id: int("id").autoincrement().primaryKey(), courseId: int("courseId").notNull(), clientUserId: int("clientUserId").notNull(), status: mysqlEnum("status", ["active", "paused", "cancelled"]).default("active").notNull(), grantedAt: timestamp("grantedAt").defaultNow().notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ courseClientIndex: uniqueIndex("course_access_course_client_idx").on(table.courseId, table.clientUserId) }));
export const moduleProgress = mysqlTable("module_progress", { id: int("id").autoincrement().primaryKey(), moduleId: int("moduleId").notNull(), clientUserId: int("clientUserId").notNull(), status: mysqlEnum("status", ["locked", "unlocked", "completed"]).default("locked").notNull(), completedAt: timestamp("completedAt"), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ moduleClientIndex: uniqueIndex("module_progress_module_client_idx").on(table.moduleId, table.clientUserId) }));

export const workoutLogs = mysqlTable("workout_logs", { id: int("id").autoincrement().primaryKey(), clientUserId: int("clientUserId").notNull(), title: varchar("title", { length: 160 }).notNull(), durationMinutes: int("durationMinutes").notNull(), notes: text("notes"), loggedAt: timestamp("loggedAt").defaultNow().notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ clientIndex: index("workout_logs_client_idx").on(table.clientUserId) }));
export const weightEntries = mysqlTable("weight_entries", { id: int("id").autoincrement().primaryKey(), clientUserId: int("clientUserId").notNull(), weight: decimal("weight", { precision: 6, scale: 2 }).notNull(), unit: varchar("unit", { length: 8 }).default("kg").notNull(), loggedAt: timestamp("loggedAt").defaultNow().notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ clientIndex: index("weight_entries_client_idx").on(table.clientUserId) }));
export const foodLogs = mysqlTable("food_logs", { id: int("id").autoincrement().primaryKey(), clientUserId: int("clientUserId").notNull(), meal: varchar("meal", { length: 80 }).notNull(), calories: int("calories"), notes: text("notes"), loggedAt: timestamp("loggedAt").defaultNow().notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ clientIndex: index("food_logs_client_idx").on(table.clientUserId) }));
export const checkIns = mysqlTable("check_ins", { id: int("id").autoincrement().primaryKey(), clientUserId: int("clientUserId").notNull(), mood: int("mood").notNull(), energy: int("energy").notNull(), wins: text("wins"), blockers: text("blockers"), submittedAt: timestamp("submittedAt").defaultNow().notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ clientIndex: index("check_ins_client_idx").on(table.clientUserId) }));
export const trainerFeedback = mysqlTable("trainer_feedback", { id: int("id").autoincrement().primaryKey(), trainerUserId: int("trainerUserId").notNull(), clientUserId: int("clientUserId").notNull(), targetType: mysqlEnum("targetType", ["checkIn", "workout", "food"]).notNull(), targetId: int("targetId").notNull(), parentId: int("parentId"), body: text("body").notNull(), editedAt: timestamp("editedAt"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ clientIndex: index("trainer_feedback_client_idx").on(table.clientUserId), targetIndex: index("trainer_feedback_target_idx").on(table.targetType, table.targetId) }));
export const notifications = mysqlTable("notifications", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), kind: varchar("kind", { length: 48 }).notNull(), title: varchar("title", { length: 160 }).notNull(), body: text("body").notNull(), readAt: timestamp("readAt"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ userIndex: index("notifications_user_idx").on(table.userId) }));

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type ClientProfile = typeof clientProfiles.$inferSelect; export type Course = typeof courses.$inferSelect; export type CourseModule = typeof modules.$inferSelect; export type ModuleProgress = typeof moduleProgress.$inferSelect;
